---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: hyprome
# description will be included in the image's metadata
description: hyprome; my personal OS image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: /

  # Install additional packages
  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-43/che-nerd-fonts-fedora-43.repo
      - https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_Rawhide/home:TheLocehiliosan:yadm.repo
      - https://copr.fedorainfracloud.org/coprs/tofik/nwg-shell/repo/fedora-43/tofik-nwg-shell-fedora-43.repo
    install:
      # Hyprland extras (wayblue uses hyprpaper, we use swww)
      - swww
      - hyprpolkitagent
      - nwg-displays
      - wlogout
      # Shell & CLI tools
      - zsh
      - nerd-fonts
      - yadm
      - lsd
      - fastfetch
      - cliphist
      - zoxide
      - fd-find
      - below
      - gitleaks
      # System services
      - tailscale
      - moby-engine
      - podman-compose
      - inotify-tools
      - rclone
      - smartmontools
      - NetworkManager-tui
      # Qt theming (qt6 packages conflict with wayblue's qt6-qtbase version)
      - qt5ct
      - qt6-qtmultimedia
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    configurations:
      - scope: user
        repo:
          # you can override the title to make inclusion of both system and user repos clearer
          title: Flathub (user)
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - com.brave.Browser
          - io.github.dvlv.boxbuddyrs
          - io.podman_desktop.PodmanDesktop
          - com.github.tchx84.Flatseal
          - org.gnome.Loupe
          - org.flameshot.Flameshot

  - type: bling
    install:
      - 1password

  - type: soar
    additional-repos: true
    auto-upgrade: true
    upgrade-interval: "3h"

  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - podman-auto-update.timer
    user:
      enabled:
        - sync-dots.service
        - hyprland-reloader.service
