---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hyprome
description: Personal atomic hyprland fedora image.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 42

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - install-1password.sh

  # Remove sway
  - type: rpm-ostree
    remove:
      - sway
      - swaybg
      - swayidle
      - swaylock
      - sway-systemd
      - sway-config-fedora
      - sddm-wayland-sway
      - grimshot
      - xdg-desktop-portal-wlr

  # Install hyprland and more, remove useless packages
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-42/solopasha-hyprland-fedora-42.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/che/nerd-fonts/repo/fedora-42/che-nerd-fonts-fedora-42.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/repo/fedora-42/ublue-os-packages.repo
      - https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_42/home:TheLocehiliosan:yadm.repo
    install:
      - hyprland
      - xdg-desktop-portal-hyprland
      - hyprpaper
      - hyprlock
      - hypridle
      - hyprpolkitagent
      - zsh
      - nerd-fonts
      - dunst
      - wlogout
      - tailscale
      - moby-engine
      - distrobox
      - podman-compose
      - qt6-qtsvg
      - qt6-qtvirtualkeyboard
      - qt6-qtmultimedia
      - inotify-tools
      - rclone
      - fd-find
      - fastfetch
      - fzf
      - cliphist
      - wl-clipboard
      - yadm
      - lsd
      - btop
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.brave.Browser
        - io.github.dvlv.boxbuddyrs
        - io.podman_desktop.PodmanDesktop
        - com.github.tchx84.Flatseal

  - type: script
    scripts:
      - install-sddm-theme.sh

  - type: systemd
    system:
      enabled:
        - tailscaled.service
        - podman-auto-update.timer
    user:
      enabled:
        - sync-dots.service
        - hyprland-reloader.service

  - type: signing
